<?php
// DADOS DA INTEGRAÇÃO COM ASSAAS

// DESENVOLVIMENTO - SANDBOX
define("ASA_ACCESS_TOKEN",'$aact_YTU5YTE0M2M2N2I4MTliNzk0YTI5N2U5MzdjNWZmNDQ6OjAwMDAwMDAwMDAwMDAwNTMyMTY6OiRhYWNoX2Y3MDE5MTBhLTZmYjYtNGRiNi1iNTM0LWZjNWMwZWU3NDU4NQ');
define("ASA_URL_API",'https://sandbox.asaas.com/');


// PRODUÇÃO
//define("ASA_URL_API",'https://www.asaas.com/');
//define("ASA_ACCESS_TOKEN",'$aact_YTU5YTE0M2M2N2I4MTliNzk0YTI5N2U5MzdjNWZmNDQ6OjAwMDAwMDAwMDAwMDAyNDcxOTQ6OiRhYWNoX2M0ZjJhMmFlLTNhMzMtNGFiZC04YTY4LTdiMjZjZWIwMWI0OA==');